services:
  node:
    container_name: reja
    restart: always
    image: akmal011216/reja-image
    ports:
      - 3003:3000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks:
      - reja_network

    command: bash -c "npm install && npm run dev"

networks:
  reja_network:
